#include QMK_KEYBOARD_H

extern keymap_config_t keymap_config;

#define BASE 0
#define META 1
#define SYMB 2
#define MCRO 3

// Fillers to make layering more clear
#define _______ KC_TRNS
#define XXXXXXX KC_NO

#ifdef RGBLIGHT_ENABLE
//Following line allows macro to read current RGB settings
extern rgblight_config_t rgblight_config;
#endif

enum custom_keycodes {
  RGB_RST = SAFE_RANGE,
  TAP_ANIM,
  DYNAMIC_MACRO_RANGE,
};

#include "dynamic_macro.h"

#define KC_SYMBEI LT(SYMB, KC_LANG2)
#define KC_METAKN LT(META, KC_LANG1)

#define KC_DRS1 DYN_REC_START1
#define KC_DRS2 DYN_REC_START2
#define KC_DMP1 DYN_MACRO_PLAY1
#define KC_DMP2 DYN_MACRO_PLAY2
#define KC_DRS  DYN_REC_STOP

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

  /* BASE
  * ,------------------------------------------------.   ,------------------------------------------------.
  * | ESC  |  Q   |  W   |  E   |  R   |  T   |  -   |   |  =   |  Y   |  U   |  I   |  O   |  P   |  BS  |
  * |------+------+------+------+------+------+------|   |-------------+------+------+------+------+------|
  * |CTLTAB|  A   |  S   |  D   |  F   |  G   |  (   |   |  )   |  H   |  J   |  K   |  L   |  ;   |  '   |
  * |------+------+------+------+------+------+------|   |------|------+------+------+------+------+------|
  * | LSFT |  Z   |  X   |  C   |  V   |  B   |  \   |   |  /   |  N   |  M   |  ,   |  .   |  UP  | RSFT |
  * |------+------+------+------+------+------+------|   |------+------+------+------+------+------+------|
  * |LGUI(K| DMP1 | DMP2 |MO(MCR| LGUI |SYMBEI| SPC  |   | ENT  |METAKN|  ALT |  `   | LEFT | DOWN | RGHT |
  * `------------------------------------------------'   `------------------------------------------------'
  *                                                                                generated by [keymapviz] */
  [BASE] = LAYOUT( \
    KC_ESC,          KC_Q,    KC_W,    KC_E,      KC_R,      KC_T,       KC_MINS,           KC_EQL,      KC_Y,     KC_U,    KC_I,     KC_O,    KC_P, KC_BSPC, \
    CTL_T(KC_TAB),   KC_A,    KC_S,    KC_D,      KC_F,      KC_G,       KC_LPRN,          KC_RPRN,      KC_H,     KC_J,    KC_K,     KC_L, KC_SCLN, KC_QUOT, \
    KC_LSFT,         KC_Z,    KC_X,    KC_C,      KC_V,      KC_B,       KC_BSLS,          KC_SLSH,      KC_N,     KC_M, KC_COMM,   KC_DOT,   KC_UP, KC_RSFT,\
    LGUI(KC_S),  KC_DMP1,  KC_DMP2,MO(MCRO),   KC_LGUI, KC_SYMBEI,        KC_SPC,           KC_ENT, KC_METAKN,  KC_RALT,  KC_GRV,  KC_LEFT, KC_DOWN, KC_RGHT  \
  ),

  /* META
  * ,------------------------------------------------.   ,------------------------------------------------.
  * |      |  1   |  2   |  3   |  4   |  5   |      |   |      |  6   |  7   |  8   |  9   |  0   | DEL  |
  * |------+------+------+------+------+------+------|   |-------------+------+------+------+------+------|
  * |      |  F1  |  F2  |  F3  |  F4  |  F5  |  {   |   |  }   | LEFT | DOWN |  UP  | RGHT |      |      |
  * |------+------+------+------+------+------+------|   |------|------+------+------+------+------+------|
  * |      |  F6  |  F7  |  F8  |  F9  | F10  |      |   |      | HOME | PGDN | PGUP | END  |      |      |
  * |------+------+------+------+------+------+------|   |------+------+------+------+------+------+------|
  * |      |      |      |      |      |      |      |   |      |      |      |      |      |      |      |
  * `------------------------------------------------'   `------------------------------------------------'
  *                                                                                generated by [keymapviz] */
  [META] = LAYOUT( \
    _______,    KC_1,    KC_2,    KC_3,    KC_4,    KC_5, _______,     _______,    KC_6,    KC_7,    KC_8,    KC_9,    KC_0, KC_DELT, \
    _______,   KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5, KC_LCBR,     KC_RCBR, KC_LEFT, KC_DOWN,   KC_UP, KC_RGHT, _______, _______, \
    _______,   KC_F6,   KC_F7,   KC_F8,   KC_F9,  KC_F10, _______,     _______, KC_HOME, KC_PGDN, KC_PGUP,  KC_END, _______, _______, \
    _______, _______, _______, _______, _______, _______, _______,     _______, _______, _______, _______, _______, _______, _______ \
  ),

  /* SYMB
  * ,------------------------------------------------.   ,------------------------------------------------.
  * |      |   !  |   @  |   #  |   $  |   %  |      |   |      |  ^   |  &   |  *   |  (   |  )   | DEL  |
  * |------+------+------+------+------+------+------|   |-------------+------+------+------+------+------|
  * |      |      |      |      |      |      |  [   |   |  ]   |      |      |      |      |      |      |
  * |------+------+------+------+------+------+------|   |------|------+------+------+------+------+------|
  * |      |      |      |      |      |      |      |   |      |      |      |      |      | PGUP |      |
  * |------+------+------+------+------+------+------|   |------+------+------+------+------+------+------|
  * |      |      |      |      |      |      |      |   |      |      |      |      | HOME | PGDN | END  |
  * `------------------------------------------------'   `------------------------------------------------'
   */
  [SYMB] = LAYOUT( \
    _______, S(KC_1), S(KC_2), S(KC_3), S(KC_4), S(KC_5), _______,     _______, S(KC_6), S(KC_7), S(KC_8), S(KC_9), S(KC_0), KC_DELT, \
    _______, _______, _______, _______, _______, _______, KC_LBRC,     KC_RBRC, _______, _______, _______, _______, _______, _______, \
    _______, _______, _______, _______, _______, _______, _______,     _______, _______, _______, _______, _______, KC_PGUP, _______, \
    _______, _______, _______, _______, _______, _______, _______,     _______, _______, _______, _______, KC_HOME, KC_PGDN,  KC_END \
  ),

  /* MCRO
  * ,------------------------------------------------.   ,------------------------------------------------.
  * |      |      |      |      |      |      |      |   |      |      |      |      |      |      |      |
  * |------+------+------+------+------+------+------|   |-------------+------+------+------+------+------|
  * |      | DRS  |      |      |      |      |      |   |      |RGB_TO|RGB_HU|RGB_SA|RGB_VA|TAP_AN|      |
  * |------+------+------+------+------+------+------|   |------|------+------+------+------+------+------|
  * |      | DRS1 | DRS2 |      |      |      |      |   |      |RGB_MO|RGB_HU|RGB_SA|RGB_VA|RGB_RS|      |
  * |------+------+------+------+------+------+------|   |------+------+------+------+------+------+------|
  * |      |      |      |      |      |      |      |   |      |      |      |      |      |      |      |
  * `------------------------------------------------'   `------------------------------------------------'
  *                                                                                generated by [keymapviz] */
  [MCRO] = LAYOUT( \
    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,     XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, \
    XXXXXXX,  KC_DRS, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,     XXXXXXX, RGB_TOG, RGB_HUI, RGB_SAI, RGB_VAI,TAP_ANIM, XXXXXXX, \
    XXXXXXX, KC_DRS1, KC_DRS2, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,     XXXXXXX, RGB_MOD, RGB_HUD, RGB_SAD, RGB_VAD, RGB_RST, XXXXXXX, \
    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,     XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX \
  )
};

bool isTapAnim = false;

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
  if (!process_record_dynamic_macro(keycode, record)) {
    return false;
  }
  switch (keycode) {
    case RGB_MOD:
      if (record->event.pressed) {
        isTapAnim = false;
      }
      break;
    case RGB_RST:
      #ifdef RGBLIGHT_ENABLE
        if (record->event.pressed) {
          eeconfig_update_rgblight_default();
          rgblight_enable();
        }
      #endif
      break;
    case TAP_ANIM:
      if (record->event.pressed) {
        isTapAnim = !isTapAnim;
      }
      break;
  }

  if (isTapAnim) {
    rgblight_mode_noeeprom(1);
    uint16_t hue = (rgblight_config.hue + 5) % 360;
    rgblight_sethsv_noeeprom(hue, rgblight_config.sat, rgblight_config.val);
  }

  return true;
}

